apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nebulous-optimiser-controller.fullname" . }}
  labels:
    {{- include "nebulous-optimiser-controller.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "nebulous-optimiser-controller.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "nebulous-optimiser-controller.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "nebulous-optimiser-controller.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: LOGDIR
              value: "{{ .Values.debug.LOGDIR }}"
            - name: ACTIVEMQ_HOST
              value: "{{ .Values.activemq.ACTIVEMQ_HOST }}"
            - name: ACTIVEMQ_PORT
              value: "{{ .Values.activemq.ACTIVEMQ_PORT }}"
            - name: ACTIVEMQ_USER
              value: "{{ .Values.activemq.ACTIVEMQ_USER }}"
            - name: ACTIVEMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "nebulous-optimiser-controller.fullname" . }}-secrets
                  key: ACTIVEMQ_PASSWORD
            - name: APP_ACTIVEMQ_HOST
              value: "{{ .Values.app.ACTIVEMQ_HOST }}"
            - name: APP_ACTIVEMQ_PORT
              value: "{{ .Values.app.ACTIVEMQ_PORT }}"
            - name: ONM_IP
              value: "{{ .Values.app.ONM_IP }}"
            - name: ONM_URL
              value: "{{ .Values.app.ONM_URL }}"
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
