apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nebulous-optimiser-controller.fullname" . }}-secrets
  labels:
    {{- include "nebulous-optimiser-controller.labels" . | nindent 4 }}
type: Opaque
data:
  ACTIVEMQ_PASSWORD: {{ .Values.secrets.ACTIVEMQ_PASSWORD | b64enc | quote }}
