/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package eu.nebulous.optimiser.controller;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class MainTest {
    @Test void noArgRunSucceeds() {
        Main main = new Main();
        assertTrue(main.call() == 0);
    }
}
