- project:
    check:
      jobs:
        - opendev-buildset-registry
        - nebulous-optimiser-controller-helm-lint
        - nebulous-optimiser-controller-build-container-images
        - nebulous-optimiser-controller-hadolint
        - nebulous-platform-apply-helm-charts
        - nebulous-optimiser-controller-java-build-java-libraries
        - nox-linters
    gate:
      jobs:
        - opendev-buildset-registry
        - nebulous-optimiser-controller-helm-lint
        - nebulous-optimiser-controller-upload-container-images
        - nebulous-optimiser-controller-hadolint
        - nebulous-platform-apply-helm-charts
        - nebulous-optimiser-controller-java-build-java-libraries
        - nox-linters
    promote:
      jobs:
        - nebulous-optimiser-controller-java-upload-java-libraries
        - nebulous-optimiser-controller-promote-container-images
