name: Publish package to GitHub Packages
on:
  push:
    branches:
      - 'main'
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'
      - uses: s4u/maven-settings-action@v2.5.0
        with:
          servers: '[
            {"id": "github","configuration": {"httpHeaders": {"property": {"name": "Authorization","value": "Bearer ${{ secrets.GITHUB_TOKEN }}"}}}}]'
      - name: Publish package
        working-directory: nebulous-requirements-extractor
        run: mvn clean source:jar deploy -DuniqueVersion=false -Dmaven.source.useDefaultManifestFile=true -DdeplyAtEnd=true -Dmaven.source.includePom=true -Dmaven.install.skip=true
        env:
          GITHUB_TOKEN: ${{ secrets.MVN_ACCESS_TOKEN }}
