name: Publish package to GitHub Packages
on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17 & Maven settings
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Build Requirements Extractor
        working-directory: nebulous-requirements-extractor
        run: mvn -B package

      - name: Publish to GitHub Packages
        working-directory: nebulous-requirements-extractor
        env:
          GITHUB_TOKEN: ${{ secrets.MVN_ACCESS_TOKEN }}
        run: mvn deploy
